version: "3.7"
services:

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042" # Port de communication natif Cassandra
      - "9160:9160" # Port legacy Cassandra Thrift
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra # Nom du service Cassandra
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - ./cassandra-data:/var/lib/cassandra # Volume pour stocker les données Cassandra

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    depends_on:
      - cassandra

  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    ports:
      - "8081:8081"
    depends_on:
      - cassandra
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1 # Définissez le nombre de cœurs souhaité
      - SPARK_WORKER_MEMORY=1G # Définissez la mémoire souhaitée
      - SPARK_DRIVER_MEMORY=512M # Mémoire pour les pilotes
      - SPARK_EXECUTOR_MEMORY=512M # Mémoire pour les exécuteurs
    volumes:
      - ./work:/home/jovyan/work
    

  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    ports:
      - "8082:8081"
    depends_on:
      - cassandra
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=512M
      - SPARK_EXECUTOR_MEMORY=512M
    volumes:
      - ./work:/home/jovyan/work

  spark-worker-3:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    ports:
      - "8083:8081"
    depends_on:
      - cassandra
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=512M
      - SPARK_EXECUTOR_MEMORY=512M
    volumes:
      - ./work:/home/jovyan/work

  pyspark-notebook:
    image: tdsparkmain:latest
    container_name: pyspark_notebook
    ports:
      - "8888:8888"
    networks:
      - my_network
    volumes:
      - ./work:/home/jovyan/work
      - ./work/model:/tmp/model_prediction
    depends_on:
      - spark-master

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Nom d'utilisateur pour l'administration de la base de données
      MONGO_INITDB_ROOT_PASSWORD: GFUGFISIUFBEIUGFIUSUF  # Mot de passe pour l'administration de la base de données
      MONGO_INITDB_DATABASE: tgvmax  # Nom de la base de données

networks:
  my_network:
    driver: bridge